# Site settings
title: QGIS with MinGW
email: theunsheydenrych@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /QGIS-MinGW # the subpath of your site, e.g. /blog/
url: "http://t-hey.github.io/QGIS-MinGW/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  t-hey

# Build settings
markdown: kramdown
